trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name='create'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('<int:customer_id>/', views.confirm_pickup, name= 'confirm_pickup'),
    path('choose_day/<str:picked_day>', views.choose_day, name = 'choose_day')
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding Django's built in routes (login and logout). Notice there is no 'login' function in accounts/views.py. Django takes care of this for us.
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate trach_collector/views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models

# Create your models here.

# TODO: Create an Employee model with properties required by the user stories

class Employee(models.Model):
    name= models.CharField( max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    address= models.CharField( max_length=200, null = True)
    zip_code= models.IntegerField(default=0)
    
    
    def __str__(self):
        return self.name

trash_collector/employees/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.apps import apps 
from datetime import date 
import calendar
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from .models import Employee
from django.db.models import Q


# Create your views here.

# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.

@login_required
def index(request):
    # This line will get the Customer model from the other app, it can now be used to query the db for Customers
    Customers = apps.get_model('customers.Customer')
    logged_in_user = request.user

    try:
        # This line will return the customer record of the logged-in user if one exists
        logged_in_employee = Employee.objects.get(user=logged_in_user)
        all_customers= Customers.objects.all()   
        date_numbers = date.today()
        day_of_week= calendar.day_name[date_numbers.weekday()] 

         
        customer_matching_zip_code= all_customers.filter(zip_code= logged_in_employee.zip_code)
        
        customer_active_account= customer_matching_zip_code.filter(Q(suspend_end__lt = date_numbers, suspend_start__gt= date_numbers) | Q(suspend_end__isnull=True, suspend_start__isnull=True));
        
        customer_pickup_weekly_and_one_time= customer_active_account.filter(Q(one_time_pickup= date_numbers) | Q(weekly_pickup= day_of_week )) 
        
        customer_ready_for_pickup= customer_pickup_weekly_and_one_time.filter(Q(date_of_last_pickup__lt = date_numbers) |Q(date_of_last_pickup__isnull=True))
        
        
        context = {
            'logged_in_employee': logged_in_employee,
            'Customer': Customers,
            'all_customers': all_customers,
            'date_numbers': date_numbers,
            'day_of_week': day_of_week,
            'customer_matching_zip_code': customer_matching_zip_code,            
            'customer_active_account': customer_active_account,
            'customer_ready_for_pickup': customer_ready_for_pickup,
        }


        return render(request, 'employees/index.html', context)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('employees:create'))
    
    
    
    



@login_required
def create(request):
    logged_in_user = request.user
    if request.method== "POST":
        name_from_form = request.POST.get('name')
        address_from_form = request.POST.get('address')
        zipcode_from_form= request.POST.get('zip_code')
        new_empyloyee= Employee( name=name_from_form, user=logged_in_user, address=address_from_form, zip_code=zipcode_from_form)
        new_empyloyee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/create.html')





@login_required
def edit_profile(request):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        address_from_form = request.POST.get('address')
        zip_from_form = request.POST.get('zip_code')        
        logged_in_employee.name = name_from_form
        logged_in_employee.address = address_from_form
        logged_in_employee.zip_code = zip_from_form        
        logged_in_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        context = {
            'logged_in_employee': logged_in_employee
        }
        return render(request, 'employees/edit_profile.html', context)



def confirm_pickup(request, customer_id): 
    
    
    try:
        Customer = apps.get_model('customers.Customer')   
        customer_to_update = Customer.objects.get(id=customer_id)
        customer_to_update.balance += 20
        customer_to_update.date_of_last_pickup = date.today()
        customer_to_update.save()
        return  HttpResponseRedirect(reverse('employees:index'))
    except ObjectDoesNotExist:        
        return render(request,'employees/index.html')
        



@login_required   
def choose_day(request, picked_day):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)    
#     customer_on_tuesday=  customer_matching_zip_code.filter(weekly_pickup= 'tuesday')
#     customer_on_thursday=  customer_matching_zip_code.filter(weekly_pickup= 'wednesday')
#     customer_on_friday=     customer_matching_zip_code.filter(weekly_pickup= 'friday')
#     customer_on_saturday=   customer_matching_zip_code.filter(weekly_pickup= 'saturday')
    day_of_week= picked_day
    try:
        Customer = apps.get_model('customers.Customer')
        all_customers= Customer.objects.all() 
        customer_matching_zip_code = all_customers.filter(zip_code=logged_in_employee.zip_code)
        customer_on_monday=   customer_matching_zip_code.filter(weekly_pickup= day_of_week)
        context = {
            'logged_in_employee': logged_in_employee,
            'customer_matching_zip_code': customer_matching_zip_code,
            'customer_on_monday': customer_on_monday, 
            'day_of_week': day_of_week
        } 
        return render(request,'employees/choose_day.html',context)
    except ObjectDoesNotExist:     
       
        return  HttpResponseRedirect(reverse('employees:index'))

trash_collector/employees/templates/employees/choose_day.html
{% extends 'employees\employee_base.html' %}

{% block title %} Employee Home {% endblock %}

{% block header %} Scheduled Customers on {{ day_of_week}} {% endblock %}

{% block content %}

{% for customer in customer_on_monday %}

<br/>
<br/>
<br />
<br />
<div style=background-color:yellow><h3> {{customer.name}}</h3></div>

{% endfor%}

{% endblock %}

trash_collector/employees/templates/employees/create.html
{% extends 'base.html' %}

{% block title %} Employee Create {% endblock %}

{% block header %} Please Complete Registration {% endblock %}

{% block content %}

<form action="{% url 'employees:create' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name"><br />
    Address: <input type="text" name="address" id="address"><br />
    Zip Code: <input type="text" name="zip_code" id="zip_code"><br />   
    <input type="submit" value="Register">
</form>

{% endblock %}

trash_collector/employees/templates/employees/edit_profile.html
{% extends 'employees\employee_base.html' %}

{% block title %} Employee Profile Edit {% endblock %}

{% block header %} Update Your Information {% endblock %}

{% block content %}
<br />
<form action="{% url 'employees:edit_profile' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name" value="{{logged_in_employee.name}}">
    <br />
    <br />
    Address: <input type="text" name="address" id="address" value="{{logged_in_employee.address}}">
    <br />
    <br />
    Zip Code: <input type="text" name="zip_code" id="zip_code" value="{{logged_in_employee.zip_code}}">
    <br />
    <input type="submit" value="Submit">
</form>

{% endblock %}

trash_collector/employees/templates/employees/employee_base.html
{% extends 'base.html' %}

{% block navbar %}
    <a class="nav-item nav-link" href="{% url 'employees:index' %}">Home</a>
    <a class="nav-item nav-link" href="{% url 'employees:edit_profile' %}">Edit Profile</a>
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'employees\employee_base.html' %}

{% block title %} Employee Home {% endblock %}

{% block header %} Employee Portal {% endblock %}

{% block content %}
  {% if user.is_authenticated %}
  <br />
  <br />
  <br />

   <h3> Hello {{ logged_in_employee.name }}!</h3>
   <h4>Employee Zipcode: {{logged_in_employee.zip_code }}</h4><br />
    <br />
    <br />
    <h3>Todays Date: {{ date_numbers }}</h3>
    <br />
    <h3>Select Day To View Scheduled Customer Pickups</h3>
    <div class="btn-group">
    <button class="button" class="btn btn-primary"> <a href="{% url 'employees:choose_day' 'monday' %}"> Monday</a></button> 
    <button class="button" class="btn btn-primary"> <a href="{% url 'employees:choose_day' 'tuesday' %}">Tuesday</a>  </button> 
    <button class="button" class="btn btn-primary"> <a href="{% url 'employees:choose_day' 'wednesday' %}">Wednesday</a> </button> 
    <button class="button" class="btn btn-primary"> <a href="{% url 'employees:choose_day' 'thursday' %}">Thursday</a> </button> 
    <button class="button" class="btn btn-primary"> <a href="{% url 'employees:choose_day' 'friday' %}">Friday</a> </button> 
    <button class="button" class="btn btn-primary"> <a href="{% url 'employees:choose_day' 'saturday' %}">Saturday</a> </button> 
    </div>
    <br />
    <br />  
    <h3>Scheduled Pickups for today:</h3>    
    {% for customer in customer_ready_for_pickup %}
    <h3> {{customer.name}} </h3> <button class="button" class="btn btn-primary"> <a href="{% url 'employees:confirm_pickup' customer.id %}"> Confirm Pickup</a></button>

    {% endfor %}  
    
    
    <br />
    <br />

 

    

  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/look.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>